export {default as Home} from './Home/Home'
export {default as Popular} from './Popular/Popular'
export {default as TopRated} from './TopRated/TopRated'
export {default as NowP} from './NowP/NowP'
export {default as ShowP} from './Show/Show'